### ISSUE TITLE
Requirements Elicitation

### ISSUE THREAD

**Issue by idilgun** [AyranIsTheNewRaki/Herodot#1]
We will have to come up with a requirements document, the elicitation will be done in class. We should come up with a set of questions. 

I have started a document: https://docs.google.com/document/d/1MwycwU6IUS_jqmdIsPUoqPDHf_spUdtul7zbJMtrYZ4/edit?usp=sharing

Let's all add the questions we can think of asking in class on Monday Feb 13

**Comment by idilgun** [comment]
After discussion in class, lets keep to wiki instead of using google docs. I have started working on the requirements, please all feel free to join in and also give feedback. Here's the [wiki page](https://github.com/AyranIsTheNewRaki/SWE574/wiki/Requirements-Specification)

**Comment by cantux** [comment]
mobile app discussion in class:

App can create an heritage item i.e add new content.

Also the app should be able to navigate to a website from the application and create annotation on that page.

**Comment by erenerdogannn** [comment]
@taygungdmr and @uyguronur shared their notes on Slack. I added my notes on theirs and share it on Slack again.

**Comment by idilgun** [comment]
@erenerdogannn Do you mind sharing the final notes here, or directly the wiki so that we can close this issue?

**Comment by erenerdogannn** [comment]
Can directly upload the notes to the wiki. 

https://github.com/AyranIsTheNewRaki/Herodot/wiki/Requirements-Elicitation

However, it might be better close the issue after clarify the requirements on the class this evening.

**Comment by taygungdmr** [comment]
I think we should add a requirement describes that visitors also shall be able to add annotations as Ms. Uskudarli stated on the previous class.

**Comment by uyguronur** [comment]
As Ms. Uskudarlı approved, we can close this issue
