### ISSUE TITLE
Mock up design regarding with interface design for Mobile App

### ISSUE THREAD

**Issue by erenerdogannn** [AyranIsTheNewRaki/Herodot#13]

**Comment by erenerdogannn** [comment]
I am planning to finish it till next week. Fyi.

**Comment by NurErtem** [comment]
https://drive.google.com/drive/folders/0B-1y2ZQCjTGvZm84a1RVWFhkZmM?usp=sharing 
collaborative design mock up creation is in progress. eren is putting ideas and designs all together. thanks for his dedication.  work in progress to be finalized after today's elicitation session in class. the mock up is v1 of the design is to be viewed here: https://projects.invisionapp.com/share/PWAMDHHM7#/screens

**Comment by idilgun** [comment]
The following link works for the tangiable > immobile > museum user story.

https://invis.io/B8APVG6VG 

I will add an intangiable story as well

**Comment by idilgun** [comment]
added intangiable story: ritual

**Comment by erenerdogannn** [comment]
There has been another issue for Website mockup. So @idilgun you may want to rename the issue just for mobile

https://github.com/AyranIsTheNewRaki/Herodot/issues/4

**Comment by uyguronur** [comment]
As Ms. Uskudarlı approved, we can close this issue
