### ISSUE TITLE
icon for heredot 

### ISSUE THREAD

**Issue by NurErtem** [AyranIsTheNewRaki/Herodot#16]
![heredoticon](https://cloud.githubusercontent.com/assets/22472032/23574725/73fc518e-008a-11e7-8a6b-40ee304e4fb3.png)
since we are working on mockups now, do you think it might be a good idea to work on the heredot icon. here is a draft which we can vote on: any other suggestions?

https://github.com/AyranIsTheNewRaki/Herodot/raw/master/Documents/DocNur/HeredotIcon.png

**Comment by taygungdmr** [comment]
It looks very nice. I also created a logo which you could find attached.

![hipsterlogogenerator_1488624420735](https://cloud.githubusercontent.com/assets/15169464/23578143/dc4d1dec-00d8-11e7-9e3d-14b6df6008eb.png)

**Comment by NurErtem** [comment]
This looks more pro definetly. The other needs some work.

**Comment by uyguronur** [comment]
both looks good thanks.

@NurErtem 's one is icon whereas @taygungdmr 's is kind of logo. Maybe we can combine them.

**Comment by idilgun** [comment]
I liked the idea with H and infinity - I created a sample to use for the mockups but the tool I used didn't let me add images so it's not in the mockups but we could use this or I think work on this idea

![infinity-xxl](https://cloud.githubusercontent.com/assets/15154813/23599675/25ee469c-024b-11e7-83e9-f20eb513a7a6.jpg)

**Comment by ebolat** [comment]
Nice logo ideas so far. We should save them as vector image.

**Comment by NurErtem** [comment]
reopening since @erenerdogannn suggested that he can turn the icon into vector as @ebolat suggested.

**Comment by NurErtem** [comment]
![heredoticonv2](https://cloud.githubusercontent.com/assets/22472032/23850445/2de38540-07e8-11e7-8ffd-3434b75dfd0f.jpg) here is v2 of the icon
