### ISSUE TITLE
Create a base UI project

### ISSUE THREAD

**Issue by uyguronur** [AyranIsTheNewRaki/Herodot#17]
Create a base UI project with angularjs2.  Base project should support general structure of angularjs2 and a basic authentication and navigation should be added.

**Comment by erenerdogannn** [comment]
I finished and commit the Web UI design

**Comment by idilgun** [comment]
@uyguronur and @erenerdogannn I believe we can either close this issue or extend it with registration functionality and updating the milestone to Sprint5.
