### ISSUE TITLE
Create project plan

### ISSUE THREAD

**Issue by uyguronur** [AyranIsTheNewRaki/Herodot#18]
We should create a project plan with milestones and deadlines

**Comment by cantux** [comment]
Here are some of the big blocks of the app:

* Web
  * Front-end
    * Smallest possible base project (there is a high chance that this would take too long due to many subjective approaches on tools/frameworks)
    * Find a UI toolkit, 
    * Annotation integrations
    * Heritage item views
  * Back-end
    * Base Project
       * Find a UI toolkit, decide on templating(this will also effect frontend) 
    * Annotation integrations
    * Heritage item models (DB?)
       * Start with single properties
       * Enhance to support array/set of properties
* Mobile ??

**Comment by NurErtem** [comment]
do you think ms project would be a good option for this? if yes, i know @taygungdmr is good at project planning. maybe @taygungdmr and I can start working on a draft to be confirmed by the team for next week @AyranIsTheNewRaki/ayranisthenewraki ? any ideas? @taygungdmr

**Comment by NurErtem** [comment]
a draft version of pp is posted under
 https://drive.google.com/drive/folders/0B-1y2ZQCjTGvZm84a1RVWFhkZmM

**Comment by taygungdmr** [comment]
I completed the project plan on GanttPro but it has some restricted features for basic version. Export and share features are only available for the pro version.

**Comment by taygungdmr** [comment]
Dear @NurErtem, could you please log in to GanttPro with credentials below and copy-paste that project plan on Microsoft Project since I don't have it on my system anymore. 

**Sign in credentials:** 

e-mail: taygun.gokdemir@hotmail.com
password: Herodot2017

**GanttPro Link**: https://app.ganttpro.com/#!/app/home

**Comment by NurErtem** [comment]
v1 and v2 of the project plan along with the milestone and deliverable integration is finalized in the team meeting on 3 april 2017
