### ISSUE TITLE
How should we handle project planning

### ISSUE THREAD

**Issue by idilgun** [AyranIsTheNewRaki/Herodot#2]
We should come up with a way to plan the project tasks.

What tools should we use? 

Individual tracking and team tracking will be done separately, we should decide on how we will uniformly report these at the end of semester.

**Comment by uyguronur** [comment]
Project management decided as follows: https://github.com/AyranIsTheNewRaki/Herodot/wiki/Project-and-Development-Management
Group communications will be here: https://github.com/AyranIsTheNewRaki/Herodot/wiki/Group-Communication
Contributing guidelines here: https://github.com/AyranIsTheNewRaki/Herodot/wiki/Contributing-Guidelines

These are all we decided, so I am closing this issue
