### ISSUE TITLE
What is the Web Annotation Data Model

### ISSUE THREAD

**Issue by idilgun** [AyranIsTheNewRaki/Herodot#3]
We should research what the Web Annotation Data Model is and its use cases.

**Comment by cantux** [comment]
We have to limit our scope but if we ever like to authenticate our users, following seems like a decent scheme: http://docs.annotatorjs.org/en/v1.2.x/authentication.html

**Comment by cantux** [comment]
Resources we have found so far (mostly by @idilgun and @ebolat )
* http://linkeddata.org/
* https://en.wikipedia.org/wiki/Resource_Description_Framework
* https://www.w3.org/TR/ldp/

Resources that must be read/understood/discussed by whole group:

* https://www.w3.org/TR/annotation-model
* https://www.w3.org/TR/json-ld/
* https://www.w3.org/TR/2017/PR-annotation-vocab-20170117/
* https://www.w3.org/TR/2017/PR-annotation-protocol-20170117/

Web Annotation Protocol server implementation with Java Spring (passes http://w3c.github.io/web-annotation/protocol/wd/ tests):

* https://github.com/dlcs/elucidate-server

Note: I haven't been able to find Java Spring implementations with Java Spring

**Comment by NurErtem** [comment]
do you think it might be a good idea to open up a section in wiki and consolidate all these under "research" or sth else?

**Comment by idilgun** [comment]
Yes, I think it would be great to have a consolidated research instead of a bunch of links, but we probably shouldn't spend a lot of time on this as well - what do you think would be a good approach?

**Comment by NurErtem** [comment]
If it is ok for the group i can consolidate this. I love research and
reading and writing.

**Comment by NurErtem** [comment]
this is in bit of a back log due to my health issues. to be updated asap
