### ISSUE TITLE
Creating Milestone Reports

### ISSUE THREAD

**Issue by taygungdmr** [AyranIsTheNewRaki/Herodot#31]
Here you could find the milestones reports about the closed ones. Feel free to give feedback.
[Milestone Report for Sprint1.docx](https://github.com/AyranIsTheNewRaki/Herodot/files/907801/Milestone.Report.for.Sprint1.docx)
[Milestone Report for Sprint2.docx](https://github.com/AyranIsTheNewRaki/Herodot/files/907802/Milestone.Report.for.Sprint2.docx)
[Milestone Report for Sprint3.docx](https://github.com/AyranIsTheNewRaki/Herodot/files/907804/Milestone.Report.for.Sprint3.docx)
[Milestone Report for Sprint4.docx](https://github.com/AyranIsTheNewRaki/Herodot/files/907803/Milestone.Report.for.Sprint4.docx)

**Comment by idilgun** [comment]
I think they look good, will we add these to wiki for easier future reference?

**Comment by ebolat** [comment]
It looks really nice. As @idilgun mentioned, we should add these as a wiki page.

**Comment by NurErtem** [comment]
moved issue in review, added appropriate tags and categories for project management board viewing.
