### ISSUE TITLE
Mock up design regarding with interface design for Website

### ISSUE THREAD

**Issue by taygungdmr** [AyranIsTheNewRaki/Herodot#4]

**Comment by erenerdogannn** [comment]
I finished the web site mockup. Invision tool is used for adding interactions to the mock-up.

https://projects.invisionapp.com/share/PWAMDHHM7#/screens

**Comment by erenerdogannn** [comment]
I finished the web site mockup. Invision tool is used for adding interactions to the mock-up.

https://projects.invisionapp.com/share/PWAMDHHM7#/screens

**Comment by erenerdogannn** [comment]
New mockup design is available in this link

https://invis.io/BPAQ32HEG

**Comment by uyguronur** [comment]
As Ms. Uskudarlı approved, we can close this issue
