### ISSUE TITLE
[BUG] API gives HTTP 401 Unauthorized when sending GET request to /heritage and /heritage/{id}

### ISSUE THREAD

**Issue by uyguronur** [AyranIsTheNewRaki/Herodot#74]
Hi 

API gives HTTP 401 Unauthorized when sending GET request to /heritage and /heritage/{id}. However according to our requirement 18 on https://github.com/AyranIsTheNewRaki/Herodot/wiki/Requirements-Elicitation we should allow visitors to see this pages as well. So can we please remove authentication requirement from these two api's?

Thanks

**Comment by ebolat** [comment]
Ohh. I'm on it. Thanks @uyguronur

**Comment by ebolat** [comment]
Fixed.
