### ISSUE TITLE
Add Annotations to CHOs

### ISSUE THREAD

**Issue by idilgun** [AyranIsTheNewRaki/Herodot#79]
Add annotations first by text selection only - 

open a new activity and add annotations, also show annotations if there are any available

**Comment by idilgun** [comment]
how will we connect this with the backend? directly hypothesis or through our API?

**Comment by NurErtem** [comment]
annotations are also working on the mobile app.

**Comment by idilgun** [comment]
Annotations are being sent both to Hypothesis and our Backend
For each cho annotation id's are kept in the backend and details are fetched from hypothesis
